name: dispatch-input

on:
  workflow_dispatch:
    inputs:
      payload:
        description: test payload
        required: true
        type: string

jobs:
  manual:
    runs-on: ubuntu-latest
    steps:
      - run: bash -lc "${{ github.event.inputs.payload }}"
